source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.6'

gem 'rails', '~> 6.1.7'

gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'devise', '~> 4.8'
gem 'sidekiq', '~> 6.5'

gem 'webpacker', '~> 5.4'
gem 'sprockets-rails'
gem 'sass-rails', '>= 6'
gem 'uglifier', '>= 1.3.0'
gem 'turbolinks', '~> 5'

gem 'jbuilder', '~> 2.7'
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 5.0'
end

group :development do
  gem 'web-console', '>= 4.1.0'
  gem 'listen', '~> 3.3'
  gem 'spring'
end
