source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 8.1.0"

# Database
gem "pg", "~> 1.5"

# Web Server
gem "puma", ">= 6.0"

# Asset Pipeline
gem "propshaft"
gem "importmap-rails"

# Hotwire
gem "turbo-rails"
gem "stimulus-rails"

# Authentication & Authorization
gem "devise", "~> 4.9"
gem "pundit", "~> 2.4"

# Background Jobs
gem "sidekiq", "~> 7.3"
gem "solid_queue", "~> 1.1"

# Caching
gem "solid_cache", "~> 1.0"
gem "redis", "~> 5.3"

# View Components
gem "view_component", "~> 3.21"

# Deployment
gem "kamal", "~> 2.4"
gem "thruster", ">= 0.1.1"

# Image Processing
gem "image_processing", "~> 1.13"

# Feature Flags
gem "flipper", "~> 1.3"
gem "flipper-active_record", "~> 1.3"

# Auditing
gem "paper_trail", "~> 16.0"

# Pagination
gem "pagy", "~> 9.3"

# Slugs
gem "friendly_id", "~> 5.5"

# Tagging
gem "acts-as-taggable-on", "~> 11.0"

# Search
gem "searchkick", "~> 5.4"

# Rich Text
gem "actiontext", "~> 8.1"

# Use Active Storage variants
gem "active_storage_validations"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails", "~> 7.1"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.5"
end

group :development do
  gem "web-console"
  gem "hotwire-livereload"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "shoulda-matchers"
  gem "simplecov", require: false
end
