source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.4"

gem "rails", "~> 7.0.8"

gem "pg", "~> 1.1"
gem "puma", "~> 5.0"

gem "turbo-rails", "~> 1.4"
gem "stimulus-rails", "~> 1.2"
gem "importmap-rails", "~> 1.2"

gem "view_component", "~> 3.5"

gem "devise", "~> 4.9"
gem "sidekiq", "~> 7.1"

gem "jbuilder"
gem "bootsnap", require: false
gem "sprockets-rails"

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "rspec-rails", "~> 6.0"
end

group :development do
  gem "web-console"
end
